repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        name: flake8 ./penaltyblog
        files: ^penaltyblog/
        args: [--config, setup.cfg]
